// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using NUnit.Framework;

[TestFixture]
public class UntitledTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void untitled()
    {
        for (int i = 0; i < 100; i++)
        {
            Console.WriteLine($"Ejecutando prueba {i + 1}/100");
            driver.Navigate().GoToUrl("http://localhost/minglr/");
            driver.Manage().Window.Size = new System.Drawing.Size(550, 692);
            driver.FindElement(By.CssSelector(".btn:nth-child(2)")).Click();
            driver.FindElement(By.Id("usrname")).Click();
            driver.FindElement(By.Id("usrname")).SendKeys("juan");
            driver.FindElement(By.Id("fname")).Click();
            driver.FindElement(By.Id("fname")).SendKeys("juan");
            driver.FindElement(By.Id("lname")).Click();
            driver.FindElement(By.Id("lname")).SendKeys("peres");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("pass")).Click();
            driver.FindElement(By.Id("pass")).SendKeys("Juan321$");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("juan@example.com");
            driver.FindElement(By.Id("regst")).Click();
        }
    }
}
